{% set version = "0.9.3" %}

package:
  name: rwa-python
  version: {{ version }}

source:
  url: https://github.com/DecBayComp/RWA-python/archive/v{{ version }}.tar.gz
  sha256: dad9b0b9284d3fae3a8c569b095aca81d7a355aeb1565b94a46d26e43aea88ff

build:
  noarch: python
  number: 0
  script: rm -f pyproject.toml; {{ PYTHON }} -m pip install --no-deps .

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - hdf5
    - h5py
    - numpy
    - pandas
    - python >=3.8
    - scipy
    - six

test:
  imports:
    - rwa
  requires:
    - pytest
  commands:
    - pytest tests/
  source_files:
    - tests/test_*.py

about:
  home: https://github.com/DecBayComp/RWA-python
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: HDF5-based serialization library for Python datatypes
  doc_url: https://rwa-python.readthedocs.io/

extra:
  recipe-maintainers:
    - francoislaurent
    - DecBayComp
