{% set version = "0.10" %}
{% set python_min = "3.8" %}

package:
  name: rwa-python
  version: {{ version }}

source:
  url: https://github.com/DecBayComp/RWA-python/archive/v{{ version }}.tar.gz
  sha256: 134624dba8c9b948a52d16862caae9c6404a88c80520a4796730de206dab7926

build:
  noarch: python
  number: 0
  script: rm -f pyproject.toml; {{ PYTHON }} -m pip install --no-deps .

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - hdf5
    - h5py
    - {{ pin_compatible('numpy') }}
    - pandas
    - python >={{ python_min }}
    - scipy
    - six

test:
  imports:
    - rwa
  requires:
    - pytest
    - python {{ python_min }}
  commands:
    - pytest tests/
  source_files:
    - tests/test_*.py

about:
  home: https://github.com/DecBayComp/RWA-python
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: HDF5-based serialization library for Python datatypes
  doc_url: https://rwa-python.readthedocs.io/

extra:
  recipe-maintainers:
    - francoislaurent
    - DecBayComp
