{% set version = "0.9.0" %}

package:
  name: rwa-python
  version: {{ version }}

source:
  url: https://github.com/DecBayComp/RWA-python/archive/v{{ version }}.tar.gz
  sha256: abcf0c4a1e067ff65654d9f8185ae90ef71a20278d3d9a427d3043d6bd8ab90b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install .

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - hdf5
    - h5py
    - numpy
    - pandas
    - python >=2.7
    - scipy
    - six

test:
  imports:
    - rwa
  requires:
    - pytest
  commands:
    - pytest tests/
  source_files:
    - tests/test_*.py

about:
  home: https://github.com/DecBayComp/RWA-python
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: HDF5-based serialization library for Python datatypes
  doc_url: https://rwa-python.readthedocs.io/

extra:
  recipe-maintainers:
    - DecBayComp
